apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-inventory-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-inventory-operator
  template:
    metadata:
      labels:
        name: redis-inventory-operator
    spec:
      serviceAccountName: testoperator
      containers:
        - name: redis-inventory-operator
          # Replace this with the built image name
          image: docker.prod.corp.scoot.co:5000/test-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - redis-inventory-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: test
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redis-inventory-operator"
