kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-inventory-operator
subjects:
- kind: ServiceAccount
  name: redis-inventory-operator
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
